import { useEffect, useMemo, useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, Bell, ChevronDown, CircleHelp, CreditCard, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, Receipt, Search, Settings, Sparkles, Target, TrendingUp, Wallet, X } from 'lucide-react'
import { financeApi } from './services/api'

const categories = ['Housing', 'Food & Dining', 'Groceries', 'Transport', 'Entertainment', 'Subscriptions', 'Salary', 'Other']
const months = ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug']
const colors = { Housing: 'blue', 'Food & Dining': 'orange', Groceries: 'green', Transport: 'purple', Entertainment: 'blue', Subscriptions: 'purple', Salary: 'green', Other: 'orange' }
const icons = { Housing: 'H', 'Food & Dining': 'F', Groceries: 'G', Transport: 'T', Entertainment: 'E', Subscriptions: 'S', Salary: 'A', Other: 'O' }
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(value)
const shortDate = value => new Date(`${value}T12:00:00`).toLocaleDateString('en-IN', { month: 'short', day: 'numeric' })

function App() {
  const [state, setState] = useState(() => financeApi.getState())
  const [signedIn, setSignedIn] = useState(() => financeApi.getSession())
  const [activeTab, setActiveTab] = useState('Overview')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [modal, setModal] = useState(null)
  const [search, setSearch] = useState('')
  const [typeFilter, setTypeFilter] = useState('all')
  const refresh = async () => setState(await financeApi.loadState())
  const changeTab = tab => { setActiveTab(tab); setMobileOpen(false) }
  useEffect(() => { if (signedIn) refresh() }, [signedIn])
  if (!signedIn) return <AuthScreen onLogin={async (email, password) => { if (!password) return; try { await financeApi.login(email, password); setSignedIn(true) } catch (error) { window.alert(error.message) } }} onRegister={async (name, email, password) => { if (!password) return; try { await financeApi.register(name, email, password); setSignedIn(true) } catch (error) { window.alert(error.message) } }} />
  const currentMonth = state.transactions.filter(item => item.date.startsWith('2026-08'))
  const income = currentMonth.filter(item => item.type === 'income').reduce((sum, item) => sum + item.amount, 0)
  const expenses = currentMonth.filter(item => item.type === 'expense').reduce((sum, item) => sum + item.amount, 0)
  const balance = 24580.2 + income - expenses
  const visible = state.transactions.filter(item => (typeFilter === 'all' || item.type === typeFilter) && `${item.merchant} ${item.category}`.toLowerCase().includes(search.toLowerCase()))
  const remove = async id => { await financeApi.deleteTransaction(id); refresh() }
  return <div className="app-shell"><Sidebar activeTab={activeTab} changeTab={changeTab} mobileOpen={mobileOpen} onLogout={() => { financeApi.logout(); setSignedIn(false) }} />{mobileOpen && <button className="scrim" onClick={() => setMobileOpen(false)} aria-label="Close navigation" />}<main className="main-content"><Topbar activeTab={activeTab} onMenu={() => setMobileOpen(true)} /><div className="page-body"><section className="page-heading"><div><p className="eyebrow">Tuesday, August 25, 2026</p><h1>Good morning, {state.user.name.split(' ')[0]} <span>✦</span></h1><p className="muted">Here is what's happening with your money this month.</p></div><button className="primary-button" onClick={() => setModal('transaction')}><Plus size={17} /> Add transaction</button></section><div className="tabs">{['Overview', 'Transactions', 'Budgets'].map(tab => <button key={tab} className={activeTab === tab ? 'tab active' : 'tab'} onClick={() => changeTab(tab)}>{tab}</button>)}</div>{activeTab === 'Overview' && <Overview income={income} expenses={expenses} balance={balance} budgets={state.budgets} transactions={visible.slice(0, 4)} onDelete={remove} />}{activeTab === 'Transactions' && <Transactions transactions={visible} search={search} setSearch={setSearch} typeFilter={typeFilter} setTypeFilter={setTypeFilter} onDelete={remove} />}{activeTab === 'Budgets' && <Budgets budgets={state.budgets} transactions={currentMonth} onAdd={() => setModal('budget')} />}{activeTab === 'Analytics' && <Analytics income={income} expenses={expenses} transactions={state.transactions} />}{['Accounts', 'Settings'].includes(activeTab) && <EmptyView title={activeTab} />}</div></main>{modal === 'transaction' && <TransactionModal onClose={() => setModal(null)} onSave={async item => { await financeApi.addTransaction(item); await refresh(); setModal(null) }} />}{modal === 'budget' && <BudgetModal onClose={() => setModal(null)} onSave={async item => { await financeApi.saveBudget(item); await refresh(); setModal(null) }} />}</div>
}

function Sidebar({ activeTab, changeTab, mobileOpen, onLogout }) { const items = [['Overview', <LayoutDashboard size={17} />], ['Transactions', <Receipt size={17} />], ['Budgets', <Target size={17} />], ['Analytics', <TrendingUp size={17} />]]; return <aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}><div className="brand"><span className="brand-mark"><Sparkles size={16} /></span><span>flo</span></div><div className="workspace"><div className="workspace-avatar">M</div><div><strong>Mayank's space</strong><small>Personal account</small></div><ChevronDown size={15} /></div><nav><p className="nav-label">Workspace</p>{items.map(([name, icon]) => <button key={name} className={`nav-item ${activeTab === name ? 'active' : ''}`} onClick={() => changeTab(name)}>{icon}<span>{name}</span></button>)}<p className="nav-label second">Manage</p><button className={`nav-item ${activeTab === 'Accounts' ? 'active' : ''}`} onClick={() => changeTab('Accounts')}><CreditCard size={17} /><span>Accounts</span></button><button className={`nav-item ${activeTab === 'Settings' ? 'active' : ''}`} onClick={() => changeTab('Settings')}><Settings size={17} /><span>Settings</span></button></nav><div className="sidebar-bottom"><div className="help-box"><CircleHelp size={17} /><span><strong>Need a hand?</strong><small>Visit our help center</small></span></div><div className="user-row"><div className="user-avatar">M</div><div><strong>Mayank Dobhal</strong><small>mayank@gmail.com</small></div><button className="more-button" onClick={onLogout} aria-label="Log out"><LogOut size={16} /></button></div></div></aside> }
function Topbar({ activeTab, onMenu }) { return <header className="topbar"><button className="menu-button" onClick={onMenu} aria-label="Open menu"><Menu size={21} /></button><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{activeTab}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={18} /><i /></button><div className="date-select">August 2026 <ChevronDown size={15} /></div><button className="avatar-small">M</button></div></header> }
function Overview({ income, expenses, balance, budgets, transactions, onDelete }) { return <><section className="stats-grid"><StatCard title="Total balance" amount={money(balance)} change="+12.8%" icon={<Wallet size={18} />} tone="sage" /><StatCard title="Income this month" amount={money(income)} change="+8.2%" icon={<ArrowDownLeft size={18} />} tone="blue" /><StatCard title="Spent this month" amount={money(expenses)} change="-4.5%" icon={<ArrowUpRight size={18} />} tone="orange" /><StatCard title="Savings rate" amount={`${income ? Math.round(((income - expenses) / income) * 100) : 0}%`} change="+3.1%" icon={<TrendingUp size={18} />} tone="purple" /></section><section className="content-grid"><CashFlow /><BudgetPanel budgets={budgets} transactions={transactions} /></section><TransactionPanel transactions={transactions} onDelete={onDelete} /></> }
function CashFlow() { return <div className="panel chart-panel"><PanelHeader title="Cash flow" action="Last 12 months" /><div className="chart-legend"><span><i className="legend-income" />Income</span><span><i className="legend-expense" />Expenses</span></div><div className="chart"><div className="y-axis"><span>₹10k</span><span>₹7.5k</span><span>₹5k</span><span>₹2.5k</span><span>₹0</span></div><div className="bars">{[42, 57, 48, 70, 61, 82, 67, 76, 89, 72, 94, 84].map((height, i) => <div className="bar-group" key={months[i]}><div className="bar income" style={{ height: `${height}%` }} /><div className="bar expense" style={{ height: `${Math.max(22, height - 35)}%` }} /><small>{months[i]}</small></div>)}</div></div></div> }
function BudgetPanel({ budgets, transactions }) { return <div className="panel budget-panel"><PanelHeader title="Budget overview" action="View all" />{budgets.slice(0, 4).map(budget => <BudgetRow key={budget.id} budget={budget} transactions={transactions} />)}</div> }
function BudgetRow({ budget, transactions }) { const spent = transactions.filter(item => item.category === budget.category).reduce((sum, item) => sum + item.amount, 0); return <div className="budget-row"><div><span>{budget.category}</span><strong>{money(spent)} of {money(budget.limit_amount)}</strong></div><div className="progress-track"><i className={colors[budget.category] || 'green'} style={{ width: `${Math.min(100, spent / budget.limit_amount * 100)}%` }} /></div></div> }
function TransactionPanel({ transactions, onDelete }) { return <section className="panel transactions-panel"><PanelHeader title="Recent transactions" action="View all transactions" /><div className="transaction-list">{transactions.length ? transactions.map(item => <TransactionRow key={item.id} item={item} onDelete={onDelete} />) : <p className="empty-state">No transactions yet.</p>}</div></section> }
function TransactionRow({ item, onDelete }) { return <div className="transaction"><div className={`merchant-icon ${colors[item.category] || 'green'}`}>{icons[item.category] || item.merchant[0]}</div><div className="transaction-info"><strong>{item.merchant}</strong><span>{item.category} <em>·</em> {shortDate(item.date)}</span></div><strong className={item.type === 'income' ? 'positive amount' : 'amount'}>{item.type === 'income' ? '+' : '-'}{money(item.amount)}</strong><button className="more-button" onClick={() => onDelete(item.id)} aria-label={`Delete ${item.merchant}`}><MoreHorizontal size={18} /></button></div> }
function Transactions({ transactions, search, setSearch, typeFilter, setTypeFilter, onDelete }) { return <section className="panel transactions-panel full-panel"><PanelHeader title="Transactions" action={`${transactions.length} entries`} /><div className="transaction-toolbar"><div className="search-field"><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search transactions" /></div><select className="filter-button" value={typeFilter} onChange={event => setTypeFilter(event.target.value)}><option value="all">All types</option><option value="income">Income</option><option value="expense">Expenses</option></select></div><div className="transaction-list">{transactions.map(item => <TransactionRow key={item.id} item={item} onDelete={onDelete} />)}</div></section> }
function Budgets({ budgets, transactions, onAdd }) { return <section className="panel full-panel"><div className="panel-header"><div><h2>Monthly budgets</h2><p className="muted">Keep your spending aligned with your goals.</p></div><button className="primary-button" onClick={onAdd}><Plus size={16} /> Add budget</button></div><div className="budget-list">{budgets.map(budget => <BudgetRow key={budget.id} budget={budget} transactions={transactions} />)}</div></section> }
function Analytics({ income, expenses, transactions }) { const byCategory = useMemo(() => transactions.filter(item => item.type === 'expense').reduce((result, item) => ({ ...result, [item.category]: (result[item.category] || 0) + item.amount }), {}), [transactions]); return <section className="analytics-grid"><div className="panel analytics-callout"><p className="eyebrow">Financial health</p><h2>{income > expenses ? 'You are on track.' : 'Time to review spending.'}</h2><p className="muted">Your income is {money(Math.abs(income - expenses))} {income > expenses ? 'higher' : 'lower'} than expenses this month.</p></div><div className="panel"><PanelHeader title="Spending by category" action="August" />{Object.entries(byCategory).map(([category, value]) => <div className="analytics-row" key={category}><span>{category}</span><strong>{money(value)}</strong><div className="progress-track"><i className={colors[category] || 'green'} style={{ width: `${Math.min(100, value / expenses * 100)}%` }} /></div></div>)}</div></section> }
function EmptyView({ title }) { return <section className="panel empty-view"><Settings size={30} /><h2>{title}</h2><p className="muted">This workspace is ready for your account details.</p></section> }
function StatCard({ title, amount, change, icon, tone }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><span className="stat-title">{title}</span><strong className="stat-amount">{amount}</strong><span className="stat-change">{change} <small>vs last month</small></span></div> }
function PanelHeader({ title, action }) { return <div className="panel-header"><h2>{title}</h2><button className="text-button">{action} <ChevronDown size={14} /></button></div> }
function AuthScreen({ onLogin, onRegister }) { const [register, setRegister] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState('mayank@gmail.com'); const [password, setPassword] = useState('demo'); return <div className="auth-screen"><div className="auth-brand"><span className="brand-mark"><Sparkles size={16} /></span><b>flo</b></div><div className="auth-card"><p className="eyebrow">Personal finance, made clear</p><h1>{register ? 'Create your account' : 'Welcome back'}</h1><p className="muted">{register ? 'Start building a calmer money routine.' : 'Sign in to continue to your workspace.'}</p>{register && <FormInput label="Name" value={name} onChange={setName} placeholder="Mayank Dobhal" />}<FormInput label="Email" value={email} onChange={setEmail} type="email" /><FormInput label="Password" value={password} onChange={setPassword} type="password" /><button className="primary-button auth-submit" onClick={() => register ? onRegister(name, email, password) : onLogin(email, password)}>{register ? 'Create account' : 'Sign in'} <ArrowUpRight size={15} /></button><button className="auth-switch" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'New to flo? Create an account'}</button>{!register && <small className="demo-hint">Demo account: mayank@gmail.com</small>}</div></div> }
function TransactionModal({ onClose, onSave }) { const [form, setForm] = useState({ merchant: '', category: 'Food & Dining', amount: '', type: 'expense', date: '2026-08-25' }); return <Modal title="Add transaction" onClose={onClose}><FormInput label="Merchant" value={form.merchant} onChange={value => setForm({ ...form, merchant: value })} placeholder="e.g. Coffee shop" /><FormInput label="Amount" value={form.amount} onChange={value => setForm({ ...form, amount: value })} type="number" placeholder="0.00" /><div className="form-grid"><FormSelect label="Type" value={form.type} onChange={value => setForm({ ...form, type: value })} options={['expense', 'income']} /><FormSelect label="Category" value={form.category} onChange={value => setForm({ ...form, category: value })} options={categories} /></div><FormInput label="Date" value={form.date} onChange={value => setForm({ ...form, date: value })} type="date" /><ModalActions onClose={onClose} onSave={() => form.merchant && Number(form.amount) > 0 && onSave(form)} /></Modal> }
function BudgetModal({ onClose, onSave }) { const [form, setForm] = useState({ category: 'Food & Dining', limit_amount: '' }); return <Modal title="Add budget" onClose={onClose}><FormSelect label="Category" value={form.category} onChange={value => setForm({ ...form, category: value })} options={categories.filter(category => category !== 'Salary')} /><FormInput label="Monthly limit" value={form.limit_amount} onChange={value => setForm({ ...form, limit_amount: value })} type="number" placeholder="0.00" /><ModalActions onClose={onClose} onSave={() => Number(form.limit_amount) > 0 && onSave(form)} /></Modal> }
function Modal({ title, onClose, children }) { return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={event => event.stopPropagation()}><div className="modal-heading"><div><p className="eyebrow">New entry</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18} /></button></div>{children}</div></div> }
function FormInput({ label, value, onChange, ...props }) { return <label>{label}<input value={value} onChange={event => onChange(event.target.value)} {...props} /></label> }
function FormSelect({ label, value, onChange, options }) { return <label>{label}<select value={value} onChange={event => onChange(event.target.value)}>{options.map(option => <option key={option}>{option}</option>)}</select></label> }
function ModalActions({ onClose, onSave }) { return <div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={onSave}>Save</button></div> }
export default App